version: 0.2

phases:

  install:
    commands:
+     # Added commands
+     - curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+     - yum install -y nodejs
      
      # Original install command
      - npm install

  pre_build:
    commands:
      - npm run lint

  build:  
    commands:
     - npm run build

  post_build:
    commands:
      - npm test